# Form implementation generated from reading ui file 'test/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
#git add .
#git commit -m "新增主界面并修改Designer任务配置"
#git commit -m "12321"
#git push

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel
import sys 

app = QApplication(sys.argv) #创建一个应用

#print(sys.argv) #打印应用对象
windows = QWidget() #创建一个窗口
windows.setWindowTitle("PyQt6") #设置窗口标题
windows.resize(400,300) #设置窗口大小
windows.move(400,200) #设置窗口位置
windows.show() #显示窗口

label = QLabel()
label.setText("Hello PyQt6") #创建一个标签
label.move(100,100) #设置标签位置
label.resize(200,50) #设置标签大小
label.setStyleSheet("color:red;font-size:20px;") #设置标签样式
label.setParent(windows) #设置标签的父窗口
label.show()

sys.exit(app.exec()) #应用运行  并且进入消息循环等待
